engines:
  duplication:
    enabled: false
    config:
      languages:
        javascript:
          mass_threshold: 20
          exclude_paths:
            - "test/"
           
           
        
